ALTER TABLE orgs ADD COLUMN IF NOT EXISTS ai_excluded_channels TEXT[] DEFAULT '{}';
ALTER TABLE orgs ADD COLUMN IF NOT EXISTS proactive_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE orgs ADD COLUMN IF NOT EXISTS governance_settings JSONB DEFAULT '{}';

ALTER TABLE opp_activity ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

